# Generated by Django 5.1.7 on 2025-03-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_status',
            field=models.CharField(default='Absent', max_length=10),
        ),
    ]
