# Generated by Django 5.1.7 on 2025-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_working_days',
            field=models.IntegerField(default=0),
        ),
    ]
