# Generated by Django 5.1.7 on 2025-03-14 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 9, 37, 26, 392499, tzinfo=datetime.timezone.utc)),
        ),
    ]
